'use client';
import {useEffect,useRef,ReactNode} from 'react';
import {X,Search,Inbox,ArrowUpRight} from 'lucide-react';
export function Badge({children}:{children:ReactNode}){return <span className={'badge '+String(children).toLowerCase().replaceAll(' ','-')}>{children}</span>;}
export function Avatar({name,small=false}:{name:string;small?:boolean}){const colors=['blue','purple','pink','teal','orange'];return <span className={`avatar ${colors[name.charCodeAt(0)%colors.length]} ${small?'small':''}`}>{name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span>;}
export function Empty({title='Nothing here yet',text='New records will appear here.'}:{title?:string;text?:string}){return <div className="empty"><Inbox size={30}/><h3>{title}</h3><p>{text}</p></div>;}
export function SearchBox({value,onChange,placeholder='Search…'}:{value:string;onChange:(s:string)=>void;placeholder?:string}){return <div className="search"><Search size={17}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></div>;}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);return <dialog ref={ref} className="modal" onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={20}/></button></div>{children}</dialog>;}
export type Field={name:string;label:string;type?:string;required?:boolean;options?:{value:string;label:string}[];min?:string|number;max?:string|number;step?:number;wide?:boolean;placeholder?:string};
export function Form({fields,initial={},onSubmit,busy,label='Save changes',children}:{fields:Field[];initial?:Record<string,unknown>;onSubmit:(v:Record<string,unknown>)=>void;busy:boolean;label?:string;children?:ReactNode}){return <form onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const value:Record<string,unknown>={};fields.forEach(f=>{value[f.name]=f.type==='number'?(fd.get(f.name)===''?null:Number(fd.get(f.name))):f.type==='checkbox'?fd.has(f.name):fd.get(f.name)||'';});onSubmit(value);}}><div className="form-grid">{fields.map(f=><label key={f.name} className={f.wide?'wide':''}><span>{f.label}{f.required&&' *'}</span>{f.options?<select name={f.name} required={f.required} defaultValue={String(initial[f.name]??'')}><option value="">Select…</option>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea name={f.name} required={f.required} defaultValue={String(initial[f.name]??'')} maxLength={2000} rows={3}/>:f.type==='checkbox'?<input type="checkbox" name={f.name} defaultChecked={Boolean(initial[f.name])}/>:<input name={f.name} type={f.type||'text'} required={f.required} defaultValue={String(initial[f.name]??'')} min={f.min} max={f.max} step={f.step} placeholder={f.placeholder} maxLength={f.type==='text'||!f.type?200:undefined}/>}</label>)}</div>{children}<div className="form-footer"><button className="button primary" disabled={busy} type="submit">{busy?'Saving…':label}<ArrowUpRight size={16}/></button></div></form>;}
