import {Data,Employee} from './types';
export function dayKey(date:Date|string=new Date(),timezone='Asia/Karachi'):string { return new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(date)); }
export function addDays(date:string,n:number) {const d=new Date(date+'T12:00:00Z'); d.setUTCDate(d.getUTCDate()+n); return d.toISOString().slice(0,10);}
export function dateRange(start:string,end:string) { const dates:string[]=[]; if(start>end) return dates; for(let d=start;d<=end&&dates.length<367;d=addDays(d,1)) dates.push(d); return dates; }
export function offDay(date:string,data:Data) {return data.holidays.find(h=>h.date===date)?.name || (data.settings.weekend_days.includes(new Date(date+'T12:00:00Z').getUTCDay())?'Weekly off':null);}
export function leaveDays(start:string,end:string,half:boolean,data:Data) {return dateRange(start,end).filter(d=>!offDay(d,data)).length*(half?0.5:1);}
export function timeLabel(time:string|null,timezone='Asia/Karachi') {return time?new Intl.DateTimeFormat('en-GB',{timeZone:timezone,hour:'2-digit',minute:'2-digit'}).format(new Date(time)):'—';}
export function hours(checkIn:string|null,checkOut:string|null) {return checkIn&&checkOut?Math.max(0,(+new Date(checkOut)-+new Date(checkIn))/3600000):0;}
export function attendanceStatus(employeeId:string,date:string,data:Data) { const a=data.attendance.find(a=>a.employee_id===employeeId&&a.work_date===date); if(a?.check_in){if(!a.check_out) return date<dayKey(new Date(),data.settings.timezone)?'Missing entry':'Checked in'; const t=timeLabel(a.check_in,data.settings.timezone).split(':').map(Number);const s=data.settings.work_start.split(':').map(Number);return t[0]*60+t[1]>s[0]*60+s[1]+data.settings.grace_minutes?'Late':'Present';} if(data.leaves.some(l=>l.employee_id===employeeId&&l.status==='approved'&&l.start_date<=date&&l.end_date>=date&&!offDay(date,data)))return 'On leave';if(offDay(date,data))return 'Off day';const employee=data.employees.find(e=>e.id===employeeId);if(date>dayKey(new Date(),data.settings.timezone)||(employee&&date<employee.joined_on))return 'Scheduled'; return 'Absent'; }
export function balance(employee:Employee,type:string,year:number,data:Data){ const allowance=type==='annual'?employee.annual_allowance:type==='sick'?employee.sick_allowance:type==='casual'?employee.casual_allowance:0;const used=data.leaves.filter(l=>l.employee_id===employee.id&&l.type===type&&l.start_date.startsWith(String(year))&&l.status==='approved').reduce((n,l)=>n+l.days,0);const pending=data.leaves.filter(l=>l.employee_id===employee.id&&l.type===type&&l.start_date.startsWith(String(year))&&l.status==='pending').reduce((n,l)=>n+l.days,0);return {allowance,used,pending,remaining:allowance-used-pending};}
export function allocationPeak(employeeId:string,start:string,end:string,percentage:number,data:Data,exclude?:string) {const relevant=data.allocations.filter(a=>a.employee_id===employeeId&&a.id!==exclude&&a.start_date<=end&&a.end_date>=start); const points=[start,...relevant.map(a=>a.start_date).filter(d=>d>=start&&d<=end)];return Math.max(...points.map(d=>percentage+relevant.filter(a=>a.start_date<=d&&a.end_date>=d).reduce((n,a)=>n+a.percentage,0)));}
export function localToISO(date:string,time:string,timezone:string) { const naive=new Date(`${date}T${time}:00Z`); let result=naive; for(let i=0;i<3;i++){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(result);const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));const shown=new Date(`${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}:${p.second}Z`);result=new Date(+result+(+naive-+shown));} return result.toISOString();}
